image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - mkaufman.HTMLHint
    - eventyret.bootstrap-4-cdn-snippet
    - kevinglasson.cornflakes-linter
    - hookyqr.beautify
    - alexcvzz.vscode-sqlite@0.10.1:9b92fe88420fffdc09632e4bd9709595