# Generated by Django 3.2 on 2021-04-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthfood',
            old_name='decs',
            new_name='description',
        ),
    ]
