# Generated by Django 3.2 on 2021-04-12 12:00

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0002_rename_decs_healthfood_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfood',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
