# Generated by Django 3.2 on 2021-04-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0005_alter_healthfood_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='title',
        ),
    ]
