# Generated by Django 3.2 on 2021-04-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0008_alter_healthfood_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfood',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthfood.manufacturer'),
        ),
    ]
