# Generated by Django 3.2 on 2021-04-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0009_alter_healthfood_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfood',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
