# Generated by Django 3.2 on 2021-04-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0010_auto_20210422_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='healthfood',
            name='maker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='healthfood.maker'),
            preserve_default=False,
        ),
    ]
