# Generated by Django 3.2 on 2021-04-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0012_auto_20210423_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthfood',
            old_name='nutrition',
            new_name='serving',
        ),
        migrations.AddField(
            model_name='healthfood',
            name='nutrition_carbs',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthfood',
            name='nutrition_fats',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthfood',
            name='nutrition_protein',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
