# Generated by Django 3.2 on 2021-04-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0013_auto_20210423_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfood',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
