# Generated by Django 3.2 on 2021-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0015_alter_healthfood_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfood',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
