# Generated by Django 3.2.1 on 2021-05-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthfood', '0016_alter_healthfood_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfood',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
