# Generated by Django 3.2.2 on 2021-05-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='book_id',
            new_name='healthfood_id',
        ),
    ]
