# Generated by Django 3.2 on 2021-05-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthfood', '0015_alter_healthfood_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('healthfood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthfood.healthfood')),
            ],
        ),
    ]
